import js from '@eslint/js'
import eslintConfigPrettier from 'eslint-config-prettier'
import eslintPluginPrettier from 'eslint-plugin-prettier'
import turboPlugin from 'eslint-plugin-turbo'
import tseslint from 'typescript-eslint'

// invariant: matches `bg-[#fff]`, `text-[13px]`, `p-[.5rem]`, `w-[calc(…)]`,
// `text-[length:…]`, but not variants such as `has-[input:focus]:`.
const ARBITRARY_VALUE =
  '/(^|[\\s:!])-?[a-z][a-z0-9-]*-\\[(#|\\d|\\.\\d|rgba?\\(|hsla?\\(|calc\\(|var\\(|length:|color:)/'
const ARBITRARY_VALUE_MESSAGE =
  'No arbitrary Tailwind values: add the value to packages/tokens and use its utility.'

/**
 * A shared ESLint configuration for the repository.
 *
 * @type {import("eslint").Linter.Config[]}
 * */
export const baseConfig = [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
      turbo: turboPlugin
    },
    rules: {
      'turbo/no-undeclared-env-vars': 'error'
    }
  },
  {
    plugins: {
      prettier: eslintPluginPrettier
    },
    rules: {
      'prettier/prettier': 'error'
    }
  },
  eslintConfigPrettier,
  {
    rules: {
      'no-console': ['error', { allow: ['warn', 'error'] }],
      // why: constitution IV forbids arbitrary Tailwind values for colours,
      // sizes and spacing; a missing value goes into packages/tokens first.
      'no-restricted-syntax': [
        'error',
        {
          selector: `Literal[value=${ARBITRARY_VALUE}]`,
          message: ARBITRARY_VALUE_MESSAGE
        },
        {
          selector: `TemplateElement[value.raw=${ARBITRARY_VALUE}]`,
          message: ARBITRARY_VALUE_MESSAGE
        },
        {
          selector:
            "JSXAttribute[name.name='style'] Property[key.name=/color|background|fill|stroke/i]",
          message: 'No inline style colours: use a token-backed utility class.'
        }
      ]
    }
  },
  {
    ignores: [
      'android/**',
      '*.config**',
      'dist/**',
      '.expo**',
      'ios/**',
      'node_modules/**',
      '.next/**',
      // why: generated by Next, Expo and nativewind on every run.
      '**/next-env.d.ts',
      '**/expo-env.d.ts',
      '**/nativewind-env.d.ts',
      // Build output, not source. `storybook-static` is committed in this repo,
      // so without this entry every lint run parses ~31MB of bundled JS and
      // takes minutes instead of seconds.
      'storybook-static/**',
      'coverage/**',
      '.turbo/**'
    ]
  }
]
